dataset:
  name: 'simonycl/p3_0.5_dataset'
  split: 'train'
  args:
    label_column: 'dataset'
    data_column: 'input'

coreset_method:
  # Supported: Uniform, Random, KMeansCentroids, KMeansRandom
  # name: 'Uniform'
  # name: 'Random'
  name: 'KMeansRandom'
  args:
    fraction: 0.1
    random_seed: 42
    encoder_config:
      batch_size: 2048
      is_sentence_transformer: True
      # model_name: 'intfloat/e5-large-v2'
      model_name: 'sentence-transformers/all-MiniLM-L6-v2'
      max_length_threshold: 4
