dataset:
  name: 'processed/sharegpt/sharegpt_data.jsonl'
  split: 'train'
  args:
    label_column: 'dataset'
    data_column: 'messages'
    idx_column: 'id'

coreset_method:
  # Supported: Uniform, Random, KMeansCentroids
  name: 'Random'
  # name: 'Random'
  # name: 'KMeansCentroids'
  args:
    fraction: 0.5
    random_seed: 42
