dataset:
  name: '/mnt/data/data-selection/data/processed/sharegpt/sharegpt_data.jsonl'
  split: 'train'
  args:
    label_column: 'dataset'
    data_column: 'messages'
    idx_column: 'id'

coreset_method:
  # Supported: Uniform, Random, KMeansCentroids
  name: 'Random'
  # name: 'Random'
  # name: 'Random'
  # name: 'KMeansCentroids'
  args:
    fraction: 0.05
    random_seed: 42
    scores_path: '/mnt/data/data-selection/data/processed/sharegpt/scores.jsonl'
    embedding_cache_path: '/mnt/data/data-selection/data/processed/sharegpt/embeddings.npy'
    encoder_config:
      batch_size: 4
      model_name: 'meta-llama/Llama-2-7b-hf'
      use_flash_attn: True
      is_8bit: False
