dataset:
  name: '/mnt/data/open-instruct/data/processed/tulu_v2/tulu_v2_data.jsonl'
  split: 'train'
  args:
    label_column: 'dataset'
    data_column: 'messages'
    idx_column: 'id'

coreset_method:
  # Supported: Uniform, Random, KMeansCentroids
  name: 'KMeansRandom'
  # name: 'Random'
  # name: 'Random'
  # name: 'KMeansCentroids'
  args:
    fraction: 0.1
    random_seed: 42
    embedding_cache_path: '/mnt/data/open-instruct/data/processed/tulu_v2/tulu_v2_embeddings.npy'
    encoder_config:
      batch_size: 4
      model_name: 'meta-llama/Llama-2-7b-hf'
      use_flash_attn: True
      is_8bit: False
